import type { Metadata } from "next";
import { Chakra_Petch, Geist } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const chakraPetchMono = Chakra_Petch({
  variable: "--font-chakra",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${chakraPetchMono.variable} antialiased bg-[radial-gradient(circle,_rgba(255,255,255,0.08)_10%,_rgba(0,0,0,1)_80%)] `}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
